### ISSUE TITLE
Docker and `AUTH=false` doesn't work

### ISSUE THREAD

**Issue by NamesMT** [sciactive/nephele#4]
I tried all variances of using `AUTH=false`, by `docker-compose.yaml`, inline docker run command, S3 storage, normal storage,... but it does not seems to work.
Setting `AUTH_USERNAME` or using `.htpasswd` does work normally.

**Comment by hperrin** [comment]
I figured it out. It is reading the env var, but `commander` sets the option to true if there is no `--no-auth` argument. Arguments take precedence over env vars, so commander's prop ends up being the value. I need to figure out how to detect that there wasn't an argument, and commander is just setting the default.

**Comment by hperrin** [comment]
This actually affects all boolean env vars that default to true (AUTH, NYMPH_REGISTRATION, and UPDATE_CHECK).

**Comment by hperrin** [comment]
This fix has been pushed up to Docker now.
